package hr.fer.oprpp1.custom.scripting.lexer;


/**
 * Class that represents a token generated by {@link SmartScriptLexer}
 * @author Marko Kremer
 *
 */
public class SmartScriptToken {
	
	
	/**
	 * Token value type {@link Object}
	 */
	private Object value;
	
	/**
	 * Token type type {@link SmartScriptTokenType}
	 */
	private SmartScriptTokenType tokenType;
	
	
	/**
	 * Constructor for class {@link SmartScriptToken}
	 * @param tokenType of type {@link SmartScriptTokenType}
	 * @param value of type {@link Object}
	 */
	public SmartScriptToken(SmartScriptTokenType tokenType, Object value) {
		this.value = value;
		this.tokenType = tokenType;
	}

	
	/**
	 * 
	 * @return property value as {@link Object}
	 */
	public Object getValue() {
		return value;
	}

	
	/**
	 * 
	 * @return property tokenType as {@link SmartScriptTokenType}
	 */
	public SmartScriptTokenType getType() {
		return tokenType;
	}

	

}
